//
// Created by radligna on 05.06.17.
//

#ifndef JIMP_EXERCISES_SEQUENTIALGENERATOR_H
#define JIMP_EXERCISES_SEQUENTIALGENERATOR_H


class SequentialGenerator {

};


#endif //JIMP_EXERCISES_SEQUENTIALGENERATOR_H
